export const env = {
  DYNAMO_LEADS_TABLE: process.env.DYNAMO_LEADS_TABLE!,
  GENERATE_REPORT_QUEUE_URl: process.env.GENERATE_REPORT_QUEUE_URl!,
  REPORTS_BUCKET_NAME: process.env.REPORTS_BUCKET_NAME!,
};
